# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VBPbpHXoZMjfIBvL2p0Mprcsxruwnlqa
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from clean import cleaning, encoder
from models import random_forest, log_reg, tree

data1 = pd.read_csv('/content/data.csv')
data1.drop(columns=['Unnamed: 0'], inplace=True)

train_X, train_Y = cleaning(data1)
train_X, train_Y = encoder(train_X, train_Y)

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=49)

rnd = random_forest(X_train, y_train)

y_pred = rnd.predict(X_test)

import pickle

f = open("bot_model.bin", "wb")
pickle.dump(rnd, f)